name: Update Go Dependencies

on:
  schedule:
    - cron: "0 23 * * Wed" # Runs every Wed
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Update Go Modules (Patches Only)
        run: |
          # Pin all sagernet deps to epoch github.com/sagernet/sing v0.5.2
          go list -m -json all | jq -r 'select(.Path | contains("sagernet") | not) | .Path' | while read pkg; do
            if [ ! -z "$pkg" ]; then
              go get -u=patch "$pkg"
            fi
          done
          go mod tidy
          go mod verify
          if git status --porcelain go.mod go.sum | grep .; then
            echo "updates_found=true" >> "$GITHUB_ENV"
            echo "updates_found=true" > push-new-updates.txt
          else
            echo "updates_found=false" >> "$GITHUB_ENV"
          fi

      - name: Report status of updates check
        run: |
          if [ "${{ env.updates_found }}" = "true" ]; then
            echo "Updates found."
            exit 0
          else
            echo "No updates found."
            exit 0
          fi

      - name: Avail status update artifact
        if: env.updates_found == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: new-updates
          path: push-new-updates.txt


      - name: Test Docker Image
        if: env.updates_found == 'true'
        run: docker build -t sing-box-test .

      - name: Test with Configuration
        if: env.updates_found == 'true'
        run: |
          set -e

          CONFIG_PATH="${{ github.workspace }}/config.json"
          echo '{
            "log": { "level": "info" },
            "inbounds": [{ "type": "direct" }],
            "outbounds": [{ "type": "block" }]
          }' > "$CONFIG_PATH"

          # Start container in detached mode and get its ID
          CONTAINER_ID=$(docker run -d -v "$CONFIG_PATH:/etc/sing-box/config.json" sing-box-test run -c /etc/sing-box/config.json)

          # Wait 5 seconds to check for the logs
          for i in {1..5}; do
            sleep 1
            docker logs "$CONTAINER_ID" > output.log 2>&1
            if grep -q "sing-box started" output.log; then
              echo "Test Passed"
              docker kill "$CONTAINER_ID"
              exit 0
            fi
          done

          echo "Test Failed: 'sing-box started' not found in container logs"
          docker kill "$CONTAINER_ID"
          exit 1

      - name: Commit and Push Changes
        if: env.updates_found == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git diff --quiet || (git add go.mod go.sum && git commit -m "chore: update dependencies" && git push)
